name: Build and Test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [created]

jobs:
  go_job_template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.10','1.11','1.12','1.13','1.14','1.15','1.16','1.17','1.18','1.19']
    name: Building on go v${{ matrix.go }} 

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Go version
        run: go version

      - name: Get dependencies
        run: go get -v ./...

      - name: Run unit tests
        run: go test -v ./...